Repository aemkulr/DSA-open-sorce, pull requests merged in 2020-10, with the labels that each got.

#4 Activity Selection
  activityselection.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#3 mergesort
  mergesort.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#5 Add heap sort in cpp
  heapSort.cpp
Labels: hacktoberfest-accepted

#7 Create treebasic.cpp
  treebasic.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#6 Create maximumSumSubarray.java
  maximumSumSubarray.java
Labels: hacktoberfest, hacktoberfest-accepted

#11 Simple Calculator
  Simple_Calculator.py
Labels: hacktoberfest, hacktoberfest-accepted

#8 Sentence length counter
  string_counter.py
Labels: hacktoberfest, hacktoberfest-accepted

#12 Letter Appearance Counter
  letter_counter.py
Labels: hacktoberfest, hacktoberfest-accepted

#13 Create bst.cpp
  bst.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#14 Create InvertBinaryTree.java
  InvertBinaryTree.java
Labels: hacktoberfest, hacktoberfest-accepted
